---
load:
  burst_size: 1
  rate:
    period: seconds
    value: 100
  units: frames

traffic:
  length:
    fixed: 512
  signature:
    stream_id: 1
    latency: start_of_frame
  packet:
    protocols:
    - ethernet:
        source: 00:10:f3:83:67:b2
        destination: 00:00:55:06:44:fe
    - ipv4:
        destination: 10.61.36.222
        source: 192.168.224.221
    - udp:
        destination: 80
        source: 80